apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook
spec:
  #副本数量
  replicas: 3
  selector:
    matchLabels:
      app: webook
      #描述你的POD是什么样的
  template:
    metadata:
      labels:
        app: webook
      #POD的具体信息
    spec:
      containers:
        - name: webook
          image: louis/webook:v0.0.1
          ports:
            - containerPort: 8080
