apiVersion: v1
kind: Pod
metadata:
  name: webook-redis
  labels:
    role: webook-redis
spec:
  containers:
    - name: webook-redis
      image: bitnami/redis:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
  restartPolicy: Always
  